### ISSUE TITLE
No license, no copyright notice is included in the project

### ISSUE THREAD

**Issue by Julien-Osman** [boussaffawalid/FeatureSelection#2]
Dear @boussaffawalid,

Your module is cited in OTB's documentation, but I found no copyright or license notice in the project repository. Can you clarify this information and make it appear in your source code? Without it, it is impossible to legally use your source code, because copyright law strictly applies and prohibits any reuse.

If you don't have any idea about this, you'll find detailed information in the Github documentation and on the Open Source Guides:

- [Licensing a repository](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository#where-does-the-license-live-on-my-repository)
- [The Legal Side of Open Source](https://opensource.guide/legal/)

Thank you very much for your work and thank you in advance for your clarifications.

Julien.

**Comment by boussaffawalid** [comment]
Hello @Julien-Osman 
I've added a license file https://github.com/boussaffawalid/FeatureSelection/blob/master/LICENSE
Feel free to let me know if there are any other concerns.

Best,
Walid

**Comment by Julien-Osman** [comment]
Thank you @boussaffawalid.
The license will appear in the next release of the OTB documentation.
It would be nice if you add the license in the README file (but you don't have to).

```
## Copyright and License

Copyright (c) 2020 Walid Boussaffa

FeatureSelection is free and open source software, distributed under the Apache2.0 license. Please refer to the [LICENSE](LICENSE) file or to the [quick summary](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) of this license on the [tl;drLegal](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)) website for more information on this matter.
```

Sincerely.
Julien

**Comment by boussaffawalid** [comment]
added README file as well :)
